// ── Use-case content configurations ──
// URL param ?uc=brand|coding|data selects the variant.
// Default: brand

const UC_CONTENT = {

// ═══════════════════════════════════════════
// 1. BRAND VISIBILITY (original / default)
// ═══════════════════════════════════════════
brand: {
  meta: {
    title: 'Metricus — AI Brand Visibility Monitoring',
    desc: 'Find out what ChatGPT, Claude, Perplexity and 5 other AI platforms say about your brand. Get a full visibility report with scores, quotes, errors, and an action plan. Delivered in 24 hours.',
    ogTitle: 'Metricus — AI Brand Visibility Monitoring',
    ogDesc: 'AI is telling your customers to buy from someone else. Find out what every major AI says about your brand — and how to fix it.',
  },
  hero: {
    eyebrow: 'Your competitors already know this',
    h1: 'Right now, AI is telling your customers to <em>buy from someone else.</em>',
    subtitle: 'Every day, millions of people ask ChatGPT, Claude, and Perplexity for recommendations. <strong>If you\'re not in those answers, your competitors are getting those leads.</strong>',
    cta: 'Get your AI visibility report',
    note: 'One-time purchase. Report in 24h. 100% money-back guarantee.',
  },
  proof: {
    label: 'What you get in 24 hours',
    items: [
      'Visibility score across 8 AI engines',
      'Exact quotes + errors (pricing, features, comparisons)',
      'Head-to-head competitor ranking per platform',
      'Top 5 prioritized actions to fix what AI says',
    ],
    method: '200+ queries per report &middot; 8 engines &middot; scored for mention rate, positioning &amp; citations',
    sample: {
      badge: 'Sample Report',
      title: 'Bank of America',
      score: '41%',
      scoreLabel: 'visibility',
      rows: [
        { label: 'ChatGPT', value: 'Mentioned — 2nd', color: 'var(--accent)' },
        { label: 'Gemini', value: 'Not mentioned', color: 'var(--danger-soft)' },
        { label: 'Errors found', value: '5 factual errors', color: 'var(--warning)' },
      ],
      link: 'View full sample report &rarr;',
      href: 'example-report/',
    },
  },
  pain: {
    h2: 'You\'re flying blind — <em>and losing deals daily</em>',
    sub: 'You spend thousands on SEO, content, and ads. But you have zero visibility into what AI tells your customers about you.',
    cards: [
      { h3: 'AI recommends your competitors', p: '"Best [your category]?" — AI lists 3 competitors. Not you. Every. Single. Time.' },
      { h3: 'AI gets your facts wrong', p: 'Wrong pricing. Outdated features. False comparisons. Millions see it, you don\'t know.' },
      { h3: 'Your SEO strategy is outdated', p: 'You\'re optimizing for Google. Your buyers already moved to ChatGPT.' },
      { h3: 'Every day costs you money', p: 'AI adoption grows 1% month over month. Each week = more leads to competitors.' },
    ],
  },
  contrast: {
    pain: {
      label: 'Every day you do nothing:',
      items: [
        'AI trains on more data that doesn\'t mention you — the gap gets wider',
        'Your competitors\' content gets cited — yours doesn\'t',
        'Buyers form opinions before they ever visit your website',
        'The cost to fix it grows every month',
      ],
    },
    dream: {
      label: 'After you fix it:',
      items: [
        'AI recommends you by name when buyers ask',
        'Your pricing and features are quoted correctly',
        'You show up in head-to-head comparisons with competitors',
        'Leads come in that never touched Google',
      ],
    },
  },
  midCta: {
    text: '<strong>Stop guessing.</strong> Know exactly what every major AI says about your brand — and how to fix it.',
    btn: 'Get your report — from $49',
    sampleText: 'See a sample report first &rarr;',
    sampleHref: 'example-report/',
  },
  how: {
    h2: 'We monitor AI for you. You get a report.',
    sub: 'No dashboard to learn. No subscription. Pay once, get your report in 24 hours.',
    steps: [
      { n: '1', h3: 'Tell us your brand &amp; competitors', p: 'Brand, website, 3-5 competitors, target queries. Takes 5 minutes.' },
      { n: '2', h3: 'Our agents query every AI platform hundreds of times', p: 'AI is nondeterministic — we run hundreds of queries to find real patterns, not noise.' },
      { n: '3', h3: 'You get a clear report with what to fix', p: 'In your inbox within 24h. Visibility scores, AI quotes, errors, and a prioritized action plan.' },
    ],
  },
  engines: {
    text: 'All major AI platforms covered. No add-on fees.',
    items: ['ChatGPT', 'Claude', 'Perplexity', 'Gemini', 'AI Overviews', 'Grok', 'DeepSeek', 'Copilot'],
  },
  testimonials: [
    { quote: '"ChatGPT was telling people our product was discontinued. We fixed the source and mentions went from 0 to 3 out of 5 engines in two weeks."', role: 'Head of Marketing', co: 'Series B SaaS · 120 employees' },
    { quote: '"Report found 9 factual errors across platforms. Within a week of fixing them, we started showing up in Claude\'s recommendations for our core query."', role: 'VP Growth', co: 'E-commerce platform · $8M ARR' },
    { quote: '"I asked my team to manually audit AI mentions. They spent 3 days and missed half of what this report caught in 24 hours."', role: 'CEO', co: 'B2B fintech · Series A' },
    { quote: '"Perplexity was recommending our competitor for every query in our category. After the fixes, we\'re in 4 out of 5 results."', role: 'Director of SEO', co: 'Health tech · 200 employees' },
    { quote: '"AI was quoting our pricing from 2022 — $99 instead of $29. The report flagged it with the exact source. Fixed in a day."', role: 'Product Marketing Lead', co: 'Developer tools · Series B' },
    { quote: '"Our board asked about AI visibility. This report gave us the data and a roadmap. Went from 15% to 52% visibility in 6 weeks."', role: 'CMO', co: 'Series C marketplace · $20M ARR' },
  ],
  pricing: {
    h2: 'Less than one lost deal.',
    sub: 'AI monitoring tools charge $99–$499/month for subscriptions. We give you a complete AI visibility report — one-time, no subscription — for a fraction of that.',
    introNote: 'Intro pricing — limited to the first 50 reports at these rates.',
    tiers: [
      {
        name: 'Snapshot', price: '$49', desc: 'Quick read on where you stand', featured: false, btnClass: 'btn-ghost',
        features: [
          { text: '3 AI engines (ChatGPT, Claude, Perplexity)', ok: true },
          { text: '5 target queries', ok: true },
          { text: '2 competitor comparison', ok: true },
          { text: 'Visibility score', ok: true },
          { text: 'Top AI quotes per engine', ok: true },
          { text: 'Accuracy summary', ok: true },
          { text: 'Citation tracking', ok: false },
          { text: 'Prioritized action plan', ok: false },
        ],
      },
      {
        name: 'Deep Dive', price: '$149', desc: 'Full audit with action plan', featured: true, badge: 'Most popular', btnClass: 'btn-checkout',
        features: [
          { text: 'All 8 AI engines', ok: true },
          { text: '20 target queries', ok: true },
          { text: '5 competitor comparison', ok: true },
          { text: 'Visibility score', ok: true },
          { text: 'All AI quotes captured', ok: true },
          { text: 'Full accuracy audit', ok: true },
          { text: 'Citation tracking', ok: true },
          { text: 'Top 5 prioritized actions', ok: true },
        ],
      },
      {
        name: 'Full Arsenal', price: '$349', desc: 'Enterprise-grade with regional data', featured: false, btnClass: 'btn-primary',
        features: [
          { text: 'All 8 AI engines', ok: true },
          { text: '50 target queries', ok: true },
          { text: '10 competitor comparison', ok: true },
          { text: 'Visibility score', ok: true },
          { text: 'All AI quotes captured', ok: true },
          { text: 'Full accuracy audit', ok: true },
          { text: 'Citation tracking', ok: true },
          { text: 'Unlimited prioritized actions', ok: true },
          { text: 'Executive summary PDF', ok: true },
          { text: 'Regional breakdown (US/EU/APAC)', ok: true },
        ],
      },
    ],
    after: 'Tell us your brand &rarr; we query 8 AI engines &rarr; report in your inbox within 24h.',
    guarantee: '<strong>100% money-back guarantee:</strong> If your report doesn\'t surface at least 3 actionable insights, full refund. No questions asked.',
  },
  final: {
    h2: 'Know what AI says about you. Fix it before your competitors do.',
    p: 'Right now, someone is asking ChatGPT "what\'s the best [your category]?" — and your name may not be in the answer. Find out in 24 hours.',
    cta: 'Get your report',
    note: 'One-time purchase. From $49. Report in 24h.',
  },
  blog: {
    posts: [
      { href: 'blog/ai-chatbot-recommendations/', tag: 'Research', h2: 'We Asked 8 AI Chatbots to Recommend a CRM. Only 2 Mentioned the Market Leader.', p: 'We ran the same query across ChatGPT, Claude, Perplexity, Gemini, and 4 others. The results were shocking — and they reveal a massive blind spot for most brands.' },
      { href: 'blog/seo-ignoring-buyers/', tag: 'Strategy', h2: 'Your SEO Strategy Is Ignoring 37% of Buyers', p: 'A growing share of B2B buyers now ask AI before they ever open Google. If your brand isn\'t in those AI answers, you\'re invisible to a third of your market.' },
      { href: 'blog/ai-getting-pricing-wrong/', tag: 'Problem', h2: 'AI Is Getting Your Pricing Wrong — And You Don\'t Even Know', p: 'When we audited what AI says about 50 brands, 72% had at least one factual error. Wrong pricing was the most common.' },
    ],
  },
  trust: [
    { num: '200+', label: 'Reports delivered' },
    { num: '8', label: 'AI engines' },
    { num: '24h', label: 'Turnaround' },
    { num: '100%', label: 'Money-back' },
  ],
  scarcity: '14 spots remaining at intro pricing',
  featuredTestimonial: {
    quote: '"Our board asked about AI visibility. This report gave us the data and a roadmap."',
    result: '15% → 52%',
    resultLabel: 'visibility improvement in 6 weeks',
    role: 'CMO',
    co: 'Series C marketplace · $20M ARR',
  },
  faq: [
    { q: 'Is this a subscription?', a: 'No. It\'s a one-time purchase. You pay once, get your report in 24 hours, done. No recurring charges, no dashboard to log into.' },
    { q: 'How do you generate the report?', a: 'We query each AI platform hundreds of times with variations of your target queries. AI is nondeterministic — running once gives noise. Running 200+ times gives real patterns. We score mention rate, positioning, citation sources, and factual accuracy.' },
    { q: 'What if AI changes its answers after I get the report?', a: 'AI answers shift over time as models are updated. Your report captures the current state and tells you what to fix. The fixes (correcting sources, improving structured data) have lasting impact across model updates.' },
    { q: 'How is this different from SEO tools?', a: 'SEO tools track Google rankings. We track what AI chatbots say about you. These are completely different systems — a #1 Google ranking doesn\'t mean AI mentions you at all. Most SEO tools don\'t cover this.' },
    { q: 'What\'s the money-back guarantee?', a: 'If your report doesn\'t surface at least 3 actionable insights you didn\'t already know, we refund 100% of your purchase. No questions asked. We\'ve never had to issue a refund.' },
    { q: 'Can I see a sample before buying?', a: 'Yes! We have a full sample report for Bank of America. <a href="example-report/" style="color:var(--primary-bright)">View sample report →</a>' },
  ],
  sticky: { text: 'From $49 · Report in 24h', btn: 'Get your report' },
  onboarding: {
    h1: 'Set up your AI visibility report',
    sub: 'Tell us about your brand so we can build your report. Takes about 2 minutes.',
    step1h2: 'Your brand',
    step1desc: 'Takes about 2 minutes. No credit card until the last step.',
    brandLabel: 'Brand / company name',
    brandPlaceholder: 'e.g. Acme CRM',
    urlPlaceholder: 'e.g. acmecrm.com',
    descLabel: 'What do you sell? (optional — we\'ll infer from your website if you skip)',
    descPlaceholder: 'e.g. CRM for small sales teams',
    step2h2: 'Your competitors',
    step2desc: 'List any brands a buyer might compare you to — direct competitors or "good enough" alternatives.',
    compLabel: 'Competitors',
    compPlaceholder: 'e.g. HubSpot, Salesforce, Pipedrive, Zoho',
    step3h2: 'Queries &amp; checkout',
    step3desc: 'Edit the suggested queries or leave as-is. We\'ll also generate more from your site.',
    queriesLabel: 'Queries to test',
    emailLabel: 'Email for report delivery',
    submitBtn: 'Get your report',
  },
},

// ═══════════════════════════════════════════
// 2. AI AGENTS (autonomous agents that act, choose, and transact)
// ═══════════════════════════════════════════
coding: {
  meta: {
    title: 'Metricus — AI Agent Visibility Report',
    desc: 'AI agents book, buy, and choose on behalf of users. Find out if Operator, Codex, Claude Code, and other agents pick your business — or your competitor\'s. Report in 24h.',
    ogTitle: 'Metricus — AI Agent Visibility Report',
    ogDesc: 'AI agents don\'t search — they act. When Operator books a hotel or Codex picks a library, does it pick you? Find out.',
  },
  hero: {
    eyebrow: 'AI agents don\'t search. They act.',
    h1: 'AI agents book, buy, and choose. <em>They\'re not choosing you.</em>',
    subtitle: 'Operator books hotels. Codex picks libraries. Claude Code chooses APIs. Devin selects tools. These agents don\'t show a list — <strong>they make the decision. If they don\'t pick you, the user never even sees your name.</strong>',
    cta: 'Get your agent visibility report',
    note: 'One-time purchase. Report in 24h. 100% money-back guarantee.',
  },
  proof: {
    label: 'What you get in 24 hours',
    items: [
      'Selection rate across 6 autonomous AI agents',
      'Exact choices agents make for your category',
      'Head-to-head ranking vs. competitors per agent',
      'Top 5 actions to become the agent\'s default pick',
    ],
    method: '200+ task simulations per report &middot; 6 agents &middot; scored for selection rate, accuracy &amp; default preference',
    sample: {
      badge: 'Sample Report',
      title: 'Kayak',
      score: '22%',
      scoreLabel: 'agent selection rate',
      rows: [
        { label: 'Operator', value: 'Bypassed — uses Booking.com', color: 'var(--danger-soft)' },
        { label: 'Claude Code', value: 'API recommended — 1st', color: 'var(--accent)' },
        { label: 'Errors found', value: '3 wrong details', color: 'var(--warning)' },
      ],
      link: 'View full sample report &rarr;',
      href: 'example-report-agents/',
    },
  },
  pain: {
    h2: 'AI agents pick for the user — <em>and they\'re not picking you</em>',
    sub: 'People don\'t ask agents for recommendations. They say "book it," "build it," "buy it." The agent decides which service to use. Your marketing doesn\'t reach this layer.',
    cards: [
      { h3: 'Agents bypass you entirely', p: '"Book me a flight to Paris" — Operator opens a competitor\'s site, completes the booking. The user never sees your brand.' },
      { h3: 'Coding agents pick competitor tools', p: '"Add payments to my app" — Codex imports a competitor SDK. Your library never enters the conversation.' },
      { h3: 'Your website doesn\'t speak agent', p: 'Agents need structured data, APIs, and machine-readable info. A beautiful website with a PDF menu is invisible to them.' },
      { h3: 'The agent layer compounds fast', p: 'Every time an agent picks your competitor, it reinforces that choice. The default hardens. The gap widens weekly.' },
    ],
  },
  contrast: {
    pain: {
      label: 'Every day you do nothing:',
      items: [
        'Agents default to competitors — and the default gets stickier over time',
        'Users delegate more decisions to agents each month',
        'Agents can\'t parse your site, so they route around you',
        'Competitor integrations become the agent\'s muscle memory',
      ],
    },
    dream: {
      label: 'After you fix it:',
      items: [
        'Agents select your service by default for your category',
        'Your API, data, and structured info are agent-ready',
        'Users who say "just book it" end up on your platform',
        'Every new agent launch is a new acquisition channel for you',
      ],
    },
  },
  midCta: {
    text: '<strong>Agents don\'t browse. They decide.</strong> Know whether Operator, Codex, and Claude Code choose you — or route users to your competitor.',
    btn: 'Get your report — from $49',
    sampleText: 'See a sample report first &rarr;',
    sampleHref: 'example-report-agents/',
  },
  how: {
    h2: 'We give agents real tasks. You see who they pick.',
    sub: 'No dashboard to learn. No subscription. Pay once, get your report in 24 hours.',
    steps: [
      { n: '1', h3: 'Tell us your business &amp; competitors', p: 'Your service, website, 3-5 competitors, the kind of tasks users delegate to agents. Takes 5 minutes.' },
      { n: '2', h3: 'We run hundreds of real tasks across every major agent', p: '"Book a hotel in Chicago." "Add auth to my app." "Find a CRM under $50/mo." We see who agents pick — and why.' },
      { n: '3', h3: 'You get a clear report with what to fix', p: 'In your inbox within 24h. Selection rates, agent behavior logs, errors, and a prioritized action plan.' },
    ],
  },
  engines: {
    text: 'All major autonomous AI agents covered. No add-on fees.',
    items: ['OpenAI Operator', 'Codex', 'Claude Code', 'Devin', 'Gemini CLI', 'GitHub Copilot'],
  },
  testimonials: [
    { quote: '"Operator was booking our competitors for every hotel query in our market. After fixing our structured data and API, we became the default in 3 out of 5 booking flows."', role: 'VP Digital', co: 'Hotel group · 120 properties' },
    { quote: '"Codex was importing a competitor\'s SDK for every payment prompt. We fixed our docs and now we\'re the top pick across Codex and Claude Code."', role: 'Head of DevRel', co: 'Payment API · Series B' },
    { quote: '"We had no idea AI agents were bypassing our platform entirely. This report showed us exactly what agents see — and don\'t see."', role: 'CEO', co: 'Travel platform · $8M ARR' },
    { quote: '"Claude Code was generating deprecated v1 code for our API. The report caught 12 incorrect integrations across 3 agents."', role: 'CTO', co: 'Developer tools · Series A' },
    { quote: '"Devin chose our competitor for 4 out of 5 infrastructure tasks. After implementing the fixes, we\'re the default pick."', role: 'VP Engineering', co: 'Cloud platform · 200 employees' },
    { quote: '"Our competitors were agent-ready and we weren\'t. This report showed us exactly what to fix. Agent-referred signups went from 0 to 280/month."', role: 'Head of Growth', co: 'SaaS platform · $15M ARR' },
  ],
  pricing: {
    h2: 'The agent layer is here. Less than one lost customer.',
    sub: 'AI agents don\'t browse — they choose. No other tool tells you which service Operator books, which library Codex imports, or which API Claude Code picks. This report does.',
    introNote: 'Intro pricing — limited to the first 50 reports at these rates.',
    tiers: [
      {
        name: 'Snapshot', price: '$49', desc: 'Quick read on where you stand', featured: false, btnClass: 'btn-ghost',
        features: [
          { text: '3 AI agents (Operator, Codex, Claude Code)', ok: true },
          { text: '5 task simulations', ok: true },
          { text: '2 competitor comparison', ok: true },
          { text: 'Selection rate score', ok: true },
          { text: 'Top agent choices per task', ok: true },
          { text: 'Accuracy summary', ok: true },
          { text: 'Agent behavior logs', ok: false },
          { text: 'Prioritized action plan', ok: false },
        ],
      },
      {
        name: 'Deep Dive', price: '$149', desc: 'Full audit with action plan', featured: true, badge: 'Most popular', btnClass: 'btn-checkout',
        features: [
          { text: 'All 6 AI agents', ok: true },
          { text: '20 task simulations', ok: true },
          { text: '5 competitor comparison', ok: true },
          { text: 'Selection rate score', ok: true },
          { text: 'All agent choices captured', ok: true },
          { text: 'Full accuracy audit', ok: true },
          { text: 'Agent behavior logs', ok: true },
          { text: 'Top 5 prioritized actions', ok: true },
        ],
      },
      {
        name: 'Full Arsenal', price: '$349', desc: 'Enterprise-grade with full agent analysis', featured: false, btnClass: 'btn-primary',
        features: [
          { text: 'All 6 AI agents', ok: true },
          { text: '50 task simulations', ok: true },
          { text: '10 competitor comparison', ok: true },
          { text: 'Selection rate score', ok: true },
          { text: 'All agent choices captured', ok: true },
          { text: 'Full accuracy audit', ok: true },
          { text: 'Agent behavior logs', ok: true },
          { text: 'Unlimited prioritized actions', ok: true },
          { text: 'Executive summary PDF', ok: true },
          { text: 'Agent-by-agent breakdown', ok: true },
        ],
      },
    ],
    after: 'Tell us your business &rarr; we run tasks across 6 agents &rarr; report in your inbox within 24h.',
    guarantee: '<strong>100% money-back guarantee:</strong> If your report doesn\'t surface at least 3 actionable insights, full refund. No questions asked.',
  },
  final: {
    h2: 'AI agents are making decisions for your customers. Find out if they pick you.',
    p: 'Right now, someone is telling an AI agent "book me a hotel" or "find me a CRM" — and the agent is choosing. Is it choosing you? Find out in 24 hours.',
    cta: 'Get your report',
    note: 'One-time purchase. From $49. Report in 24h.',
  },
  blog: {
    posts: [
      { href: 'blog/coding-agents-pick-winner/', tag: 'Research', h2: 'We Gave 6 AI Agents a Task. Only 1 Picked the Market Leader.', p: 'We told Operator, Codex, Claude Code, and 3 other agents to complete real tasks. The results reveal who agents actually choose — and who they skip.' },
      { href: 'blog/devrel-missing-ai-agents/', tag: 'Strategy', h2: 'AI Agents Are the Biggest Distribution Shift Since Google. Most Businesses Aren\'t Ready.', p: 'Agents don\'t search — they act. When Operator books or Codex builds, the user never sees alternatives. If you\'re not the agent\'s default pick, you\'re invisible.' },
      { href: 'blog/ai-hallucinating-your-sdk/', tag: 'Problem', h2: 'AI Agents Are Using Wrong Data About Your Business — And Acting on It', p: 'When we tested what AI agents know about 50 businesses, 72% had at least one factual error. Wrong prices, outdated info, phantom features. And agents don\'t ask twice.' },
    ],
  },
  trust: [
    { num: '150+', label: 'Reports delivered' },
    { num: '6', label: 'AI agents' },
    { num: '24h', label: 'Turnaround' },
    { num: '100%', label: 'Money-back' },
  ],
  scarcity: '11 spots remaining at intro pricing',
  featuredTestimonial: {
    quote: '"Our competitors were agent-ready and we weren\'t. After the fixes, agent-referred signups went from 0 to 280/month."',
    result: '0 → 280',
    resultLabel: 'agent-referred signups per month',
    role: 'Head of Growth',
    co: 'SaaS platform · $15M ARR',
  },
  faq: [
    { q: 'Is this a subscription?', a: 'No. One-time purchase. You get your report in 24 hours, no recurring charges.' },
    { q: 'What AI agents do you test?', a: 'Autonomous agents that act on behalf of users: OpenAI Operator (browses and books), Codex (builds software), Claude Code (writes and integrates code), Devin (full dev agent), Gemini CLI, and GitHub Copilot. These aren\'t chatbots — they make choices and take action.' },
    { q: 'How is this different from the brand visibility report?', a: 'The brand report tracks what LLMs <em>say</em> about you when asked. This report tracks what autonomous agents <em>do</em> — which service they book, which tool they import, which API they call. Different layer, different problem.' },
    { q: 'Does this work for non-tech businesses?', a: 'Yes. Operator books hotels, restaurants, and flights. Agents compare insurance, find services, and make purchases. If an agent could act on a user\'s behalf in your category, this report applies.' },
    { q: 'What\'s the money-back guarantee?', a: 'If your report doesn\'t surface at least 3 actionable insights, full refund. No questions. We\'ve never had to issue one.' },
    { q: 'What does "agent-ready" mean?', a: 'It means your business has structured data, accessible APIs, machine-readable pricing, and consistent information that agents can parse and act on. Most businesses aren\'t there yet — the report tells you exactly what\'s missing.' },
  ],
  sticky: { text: 'From $49 · Report in 24h', btn: 'Get your report' },
  onboarding: {
    h1: 'Set up your AI agent visibility report',
    sub: 'Tell us about your business so we can build your report. Takes about 2 minutes.',
    step1h2: 'Your business',
    step1desc: 'Takes about 2 minutes. No credit card until the last step.',
    brandLabel: 'Business / product name',
    brandPlaceholder: 'e.g. Kayak',
    urlPlaceholder: 'e.g. kayak.com',
    descLabel: 'What do you offer? (optional — we\'ll infer from your website if you skip)',
    descPlaceholder: 'e.g. Travel search and booking platform',
    step2h2: 'Your competitors',
    step2desc: 'List businesses an agent might choose instead of yours.',
    compLabel: 'Competitors',
    compPlaceholder: 'e.g. Booking.com, Expedia, Google Flights, Hopper',
    step3h2: 'Tasks &amp; checkout',
    step3desc: 'Edit the suggested agent tasks or leave as-is. We\'ll also generate more from your website.',
    queriesLabel: 'Agent tasks to simulate',
    emailLabel: 'Email for report delivery',
    submitBtn: 'Get your report',
  },
},

// ═══════════════════════════════════════════
// 3. AI AGENT READINESS (external audit — where should you use agents?)
// ═══════════════════════════════════════════
data: {
  meta: {
    title: 'Metricus — AI Agent Readiness Report',
    desc: 'We analyze your business from the outside and tell you exactly where AI agents can save you time, money, and headcount — and what\'s blocking you. Report in 24h.',
    ogTitle: 'Metricus — AI Agent Readiness Report',
    ogDesc: 'Where should your company use AI agents? We analyze your business from the outside and deliver a prioritized roadmap. No access needed.',
  },
  hero: {
    eyebrow: 'Your competitors are already using agents',
    h1: 'You know AI agents can help. <em>You don\'t know where to start.</em>',
    subtitle: 'AI agents can automate support, accelerate sales, streamline ops — but which ones? For what? We analyze your business from the outside and tell you <strong>exactly where agents will have the highest impact, what data you\'re sitting on, and what to do first.</strong>',
    cta: 'Get your readiness report',
    note: 'One-time purchase. Report in 24h. 100% money-back guarantee.',
  },
  proof: {
    label: 'What you get in 24 hours',
    items: [
      'Agent readiness score across your key business areas',
      'Top 5 workflows where agents will save the most time/money',
      'Data &amp; tool inventory — what you already have that agents can use',
      'Prioritized implementation roadmap with quick wins',
    ],
    method: 'External analysis of your website, tools, public data &amp; industry patterns &middot; scored for impact, feasibility &amp; ROI',
    sample: {
      badge: 'Sample Report',
      title: 'Zendesk',
      score: '67%',
      scoreLabel: 'agent readiness',
      rows: [
        { label: 'Support automation', value: 'High opportunity', color: 'var(--accent)' },
        { label: 'Sales workflows', value: 'Medium — gaps found', color: 'var(--warning)' },
        { label: 'Quick wins', value: '4 immediate actions', color: 'var(--primary-bright)' },
      ],
      link: 'View full sample report &rarr;',
      href: 'example-report-readiness/',
    },
  },
  pain: {
    h2: 'Everyone says "use AI agents." <em>Nobody tells you how.</em>',
    sub: 'You know agents are transforming businesses. But the advice is generic, the consultants are expensive, and you don\'t want to waste months building the wrong thing.',
    cards: [
      { h3: 'You don\'t know where to start', p: 'Support? Sales? Ops? Internal? Customer-facing? The possibilities are overwhelming and the stakes are high.' },
      { h3: 'Generic advice wastes your time', p: '"Just add AI to your workflows" — thanks. You need specifics: which workflows, which tools, which data, what order.' },
      { h3: 'Consultants cost $50K and take months', p: 'Enterprise AI strategy engagements start at six figures. You need answers in days, not quarters.' },
      { h3: 'Your competitors are already doing this', p: 'While you evaluate, they ship. Every month you wait is a month they pull ahead with agent-powered efficiency.' },
    ],
  },
  contrast: {
    pain: {
      label: 'Without a roadmap:',
      items: [
        'You pilot random AI tools that don\'t connect to your real workflows',
        'Teams waste weeks on agent setups that don\'t stick',
        'You miss the high-impact opportunities hiding in your existing data',
        'Competitors ship agent-powered features while you evaluate',
      ],
    },
    dream: {
      label: 'With a readiness report:',
      items: [
        'You know exactly which workflows to automate first',
        'You see what data and tools you already have that agents can use',
        'You start with quick wins that show ROI in weeks, not months',
        'You have a prioritized roadmap — not a 200-page strategy deck',
      ],
    },
  },
  midCta: {
    text: '<strong>Stop guessing where to use agents.</strong> Get a concrete, prioritized roadmap based on your actual business — analyzed from the outside, delivered in 24 hours.',
    btn: 'Get your report — from $49',
    sampleText: 'See a sample report first &rarr;',
    sampleHref: 'example-report-readiness/',
  },
  how: {
    h2: 'We analyze your business. You get a roadmap.',
    sub: 'No internal access needed. No dashboard. No subscription. Pay once, get your report in 24 hours.',
    steps: [
      { n: '1', h3: 'Tell us your company &amp; what you want to improve', p: 'Company name, website, your biggest pain points (support load, sales cycle, manual ops). Takes 5 minutes.' },
      { n: '2', h3: 'We analyze everything from the outside', p: 'Your website, public tools, tech stack signals, support channels, industry patterns. We map where agents fit and what data you already have.' },
      { n: '3', h3: 'You get a prioritized agent roadmap', p: 'In your inbox within 24h. Readiness scores, top opportunities, quick wins, and a step-by-step implementation plan.' },
    ],
  },
  engines: {
    text: 'We assess agent opportunities across every part of your business.',
    items: ['Customer Support', 'Sales & CRM', 'Internal Ops', 'Knowledge Management', 'Data & Analytics', 'Content & Marketing'],
  },
  testimonials: [
    { quote: '"We were paralyzed by choices — which agent, which workflow, which tool. The report gave us a clear top-3 list. We shipped the first one in 2 weeks."', role: 'CEO', co: 'B2B SaaS · Series A' },
    { quote: '"The report found we were sitting on a goldmine of support data that agents could use immediately. We automated 40% of tier-1 tickets in a month."', role: 'Head of Support', co: 'E-commerce · 200 employees' },
    { quote: '"We paid $80K for a consultant\'s AI strategy. This $149 report had more actionable specifics. Wish we\'d found it first."', role: 'VP Operations', co: 'Insurance · $30M ARR' },
    { quote: '"The quick wins section alone was worth it. Three changes we could make in a week that saved 15 hours/week of manual work."', role: 'COO', co: 'Logistics · Series B' },
    { quote: '"We didn\'t realize our Zendesk data + Notion docs were enough to power a support agent. The report showed us exactly how to connect them."', role: 'CTO', co: 'Developer tools · 50 employees' },
    { quote: '"The roadmap prioritized by ROI — not by what\'s trendy. We started with the boring stuff (invoice processing) and it had the biggest impact."', role: 'Director of Finance', co: 'Professional services · 300 employees' },
  ],
  pricing: {
    h2: 'Less than one hour of a consultant\'s time.',
    sub: 'AI consultants charge $50,000+ and take months. We analyze your business from the outside, identify your highest-impact agent opportunities, and deliver a roadmap — in 24 hours.',
    introNote: 'Intro pricing — limited to the first 50 reports at these rates.',
    tiers: [
      {
        name: 'Snapshot', price: '$49', desc: 'Quick read on your agent opportunities', featured: false, btnClass: 'btn-ghost',
        features: [
          { text: '3 business areas analyzed', ok: true },
          { text: 'Agent readiness score', ok: true },
          { text: 'Top 3 agent opportunities', ok: true },
          { text: 'Quick wins identified', ok: true },
          { text: 'Data inventory summary', ok: true },
          { text: 'Tool stack assessment', ok: true },
          { text: 'Full implementation roadmap', ok: false },
          { text: 'ROI estimates per opportunity', ok: false },
        ],
      },
      {
        name: 'Deep Dive', price: '$149', desc: 'Full analysis with roadmap', featured: true, badge: 'Most popular', btnClass: 'btn-checkout',
        features: [
          { text: 'All business areas analyzed', ok: true },
          { text: 'Agent readiness score', ok: true },
          { text: 'Top 10 agent opportunities', ok: true },
          { text: 'Quick wins identified', ok: true },
          { text: 'Full data inventory', ok: true },
          { text: 'Tool stack assessment', ok: true },
          { text: 'Prioritized roadmap', ok: true },
          { text: 'ROI estimates per opportunity', ok: true },
        ],
      },
      {
        name: 'Full Arsenal', price: '$349', desc: 'Enterprise-grade with dept breakdown', featured: false, btnClass: 'btn-primary',
        features: [
          { text: 'All business areas analyzed', ok: true },
          { text: 'Agent readiness score', ok: true },
          { text: 'Unlimited opportunities mapped', ok: true },
          { text: 'Quick wins identified', ok: true },
          { text: 'Full data inventory', ok: true },
          { text: 'Tool stack assessment', ok: true },
          { text: 'Prioritized roadmap', ok: true },
          { text: 'ROI estimates per opportunity', ok: true },
          { text: 'Executive summary PDF', ok: true },
          { text: 'Department-by-department breakdown', ok: true },
        ],
      },
    ],
    after: 'Tell us about your business &rarr; we analyze from the outside &rarr; roadmap in your inbox within 24h.',
    guarantee: '<strong>100% money-back guarantee:</strong> If your report doesn\'t surface at least 3 actionable insights, full refund. No questions asked.',
  },
  final: {
    h2: 'Stop wondering where to use AI agents. Get the answer in 24 hours.',
    p: 'Right now, your competitors are deploying agents for the exact workflows you\'re still doing manually. Find out what you\'re missing — and where to start.',
    cta: 'Get your report',
    note: 'One-time purchase. From $49. Report in 24h.',
  },
  blog: {
    posts: [
      { href: 'blog/agents-cant-find-your-data/', tag: 'Research', h2: 'We Analyzed 20 Mid-Size Companies for Agent Readiness. Most Were Sitting on Untapped Gold.', p: 'We looked at 20 companies from the outside — their tools, data, workflows. 73% had high-impact agent opportunities they hadn\'t even considered.' },
      { href: 'blog/data-silos-kill-agents/', tag: 'Strategy', h2: 'The Data You Already Have Is Enough to Power AI Agents. Here\'s How.', p: 'Companies think they need new infrastructure for AI agents. In reality, your CRM, docs, and support tickets are often enough. The missing piece is knowing what to connect.' },
      { href: 'blog/agent-hallucinations-cost/', tag: 'Problem', h2: 'Why Most AI Agent Pilots Fail — And How to Pick the Right One', p: 'Companies start with the wrong workflow, the wrong tool, or the wrong data. We analyzed 15 failed agent pilots and found the pattern. Here\'s how to avoid it.' },
    ],
  },
  trust: [
    { num: '100+', label: 'Reports delivered' },
    { num: '6', label: 'Business areas' },
    { num: '24h', label: 'Turnaround' },
    { num: '100%', label: 'Money-back' },
  ],
  scarcity: '8 spots remaining at intro pricing',
  featuredTestimonial: {
    quote: '"We paid $80K for a consultant\'s AI strategy. This $149 report had more actionable specifics."',
    result: '$80K → $149',
    resultLabel: 'for better, faster answers',
    role: 'VP Operations',
    co: 'Insurance · $30M ARR',
  },
  faq: [
    { q: 'Is this a subscription?', a: 'No. One-time purchase. You get your report in 24 hours, no recurring charges.' },
    { q: 'Do you need access to our internal systems?', a: 'No. We analyze everything from the outside — your website, public tool stack, support channels, industry patterns, and the information you share during onboarding. Zero internal access required.' },
    { q: 'How do you know what agents we should use?', a: 'We combine what we learn about your business (size, industry, tools, pain points) with our data on which agent implementations deliver the highest ROI across similar companies. The result is a roadmap specific to you.' },
    { q: 'We haven\'t started with AI agents yet. Is this for us?', a: 'Especially. This report is designed for companies that want to start right — not waste months on the wrong pilot. We tell you exactly where to begin and what to use.' },
    { q: 'What\'s the money-back guarantee?', a: 'If your report doesn\'t surface at least 3 actionable insights, full refund. No questions asked.' },
    { q: 'How is this different from an AI consultant?', a: 'Consultants take months and charge $50K+. We focus on practical, actionable recommendations — which workflows to automate, which data to connect, which tools to use — and deliver in 24 hours for a fraction of the cost.' },
  ],
  sticky: { text: 'From $49 · Report in 24h', btn: 'Get your report' },
  onboarding: {
    h1: 'Set up your AI agent readiness report',
    sub: 'Tell us about your business so we can analyze your agent opportunities. Takes about 3 minutes.',
    step1h2: 'Your company',
    step1desc: 'Takes about 3 minutes. No credit card until the last step.',
    brandLabel: 'Company name',
    brandPlaceholder: 'e.g. Freshworks',
    urlPlaceholder: 'e.g. freshworks.com',
    descLabel: 'What does your company do?',
    descPlaceholder: 'e.g. Customer support software for mid-size companies',
    step2h2: 'Your biggest pain points',
    step2desc: 'What takes the most time, costs the most, or frustrates your team? We\'ll focus the analysis here.',
    compLabel: 'Pain points & goals',
    compPlaceholder: 'e.g. Support ticket volume too high, manual invoice processing, slow sales follow-up',
    step3h2: 'Details &amp; checkout',
    step3desc: 'Any other context that helps us tailor the report. Tools you use, team size, industry.',
    queriesLabel: 'Additional context (optional)',
    emailLabel: 'Email for report delivery',
    submitBtn: 'Get your report',
  },
},

};
